[package]
name = "bdk-reserves"
version = "2.2.0"
authors = ["Richard Ulrich <richard.ulrich@aminagroup.com>"]
edition = "2018"
description = "Proof of reserves for bitcoin dev kit"
keywords = ["proof", "reserves", "bitcoin", "psbt"]
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/bitcoindevkit/bdk-reserves"

[dependencies]
bdk_wallet = { version = "2.2.0", default-features = false, features = ["std"] }
bitcoinconsensus = "0.19.0-3"
log = "^0.4"

# same version as in rust-bitcoin - I couldn't find a re-export
units = { package = "bitcoin-units", version = "0.1.0", default-features = false, features = ["alloc"] }

[dev-dependencies]
rstest = "^0.26"
bdk_wallet = { version = "2.2.0", default-features = true, features = ["test-utils"] }
bdk_electrum = "0.23.1"
bdk_tx = "0.1"
secp256k1 = { version = "0.29", features = [ "rand" ] }
electrsd = { version = "0.36", features = ["corepc-node_29_0", "electrs_0_10_6"] }
