on: [push, pull_request]

name: CI

jobs:

  build-test:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.87.0 # current
          - 1.63.0 # MSRV
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Generate cache key
        run: echo "${{ matrix.rust }} ${{ matrix.features }}" | tee .cache_key
      - name: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('.cache_key') }}-${{ hashFiles('**/Cargo.toml','**/Cargo.lock') }}
      - name: Set default toolchain
        run: rustup default ${{ matrix.rust }}
      - name: Set profile
        run: rustup set profile minimal
      - name: Add clippy
        run: rustup component add clippy
      - name: Update toolchain
        run: rustup update
      - name: Update Cargo.lock
        run: cargo update
      - name: Pin dependencies for MSRV
        if: matrix.rust == '1.63.0'
        run: |
          cargo update -p zstd-sys --precise "2.0.8+zstd.1.5.5"
          cargo update -p time --precise "0.3.20"
          cargo update -p home --precise "0.5.5"
          cargo update -p flate2 --precise "1.0.35"
          cargo update -p bzip2-sys --precise "0.1.12"
          cargo update -p ring --precise "0.17.12"
          cargo update -p once_cell --precise "1.20.3"
          cargo update -p base64ct --precise "1.6.0"
          cargo update -p minreq --precise "2.13.2"
          cargo update -p bdk_electrum --precise 0.20.1
          cargo update -p rustls:0.23.28 --precise 0.23.12
      - name: Build
        run: cargo build
      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: Test
        run: cargo test

  fmt:
    name: Rust fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set default toolchain
        run: rustup default nightly
      - name: Set profile
        run: rustup set profile minimal
      - name: Add rustfmt
        run: rustup component add rustfmt
      - name: Update toolchain
        run: rustup update
      - name: Check fmt
        run: cargo fmt --all -- --config format_code_in_doc_comments=true --check
